blueprint:
  name: Hydro-Québec Flex D
  description: '# Gestion des événements de point critique "Flex D" d''Hydro-Québec.


    Ce blueprint offre les bases pour faire la gestion des événements de pointes critiques
    dans le cadre du tarif [Flex D d''Hydro-Québec](https://www.hydroquebec.com/residentiel/espace-clients/tarifs/tarif-flex-d.html).
    Il a été créé pour fonctionner avec le projet [Hydroqc](https://hydroqc.ca) qui
    extrait les données de votre compte à partir du portail client d''Hydro-Québec.


    ## Configuration


    ### Entités de temps et de criticité de la période.

    Les valeurs des premières configurations seront autoremplies si le nom de votre
    contrat dans votre configuration hydroqc est "maison". Autrement vous devrez sélectionner
    les entités correspondantes.


    ### Actions


    Définition des actions à effectuer dans Home-Assistant lors de chaque début et
    fin de périodes.


    Vous trouverez plus de détail sur les logiques applicables pour les crédits hivernaux
    dans notre [documentation](https://hydroqc.ca/en/docs/winter-credits/).

    '
  domain: automation
  input:
    pre_heat:
      name: Début pré-chauffage
      description: Moment avant une pointe critique où nous voulons augmenter le chauffage de la résidence en vu de la pointe. Cette période se termine lorsque la pointe critique commence.
      default: sensor.hydroqc_maison_next_pre_heat_start
      selector:
        entity:
          integration: mqtt
          device_class: timestamp
          domain: sensor
          multiple: false
    peak_start:
      name: Début pointe
      description: Début de la période de pointe (sensor.hydroqc_maison_next_peak_start)
      default: sensor.hydroqc_maison_next_peak_start
      selector:
        entity:
          integration: mqtt
          device_class: timestamp
          domain: sensor
          multiple: false
    peak_end:
      name: Fin pointe
      description: Fin de la période de pointe (sensor.hydroqc_maison_next_peak_end)
      default: sensor.hydroqc_maison_next_peak_end
      selector:
        entity:
          integration: mqtt
          device_class: timestamp
          domain: sensor
          multiple: false
    pre_heat_start_action:
      name: Action de pré-chauffage
      description: Actions à effectuer avant la période de pointe critique pour
        pré-chauffer votre résidence.
      default: []
      selector:
        action: {}
    critical_peak_start_action:
      name: Action début pointe critique
      description: Actions à effectuer au début de la période de pointe critique pour
        réduire votre consommation électrique.
      default: []
      selector:
        action: {}
    critical_peak_end_action:
      name: Action fin pointe critique
      description: Actions à effectuer à la fin de la période de pointe critique pour
        rétablir votre consommation normale.
      default: []
      selector:
        action: {}
  source_url: https://raw.githubusercontent.com/hydroqc/hass-blueprint-hydroqc/main/hydroqc-flex-d.yaml
mode: parallel
trigger:
- platform: time
  at: !input pre_heat
  id: pre_heat_trigger
- platform: time
  at: !input peak_start
  id: peak_start_trigger
- platform: time
  at: !input peak_end
  id: peak_end_trigger
action:
- choose:
  - conditions:
    - condition: trigger
      id: pre_heat_trigger
    sequence: !input pre_heat_start_action
  - conditions:
    - condition: trigger
      id: peak_start_trigger
    sequence: !input critical_peak_start_action
      
  - conditions:
    - condition: trigger
      id: peak_end_trigger
    sequence: !input critical_peak_end_action
     
